import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import Banner from '@/components/banner'
import Card from '@/components/card'
import SectionCards from '@/components/section-cards'
import { getPopularVideos, getVideos } from '@/lib/videos'


export const getServerSideProps = async () => {
  const disneyVideos = await getVideos("disney trailer");
  const tvShowsVideos = await getVideos("tv shows trailers");
  const nollywoodVideos = await getVideos("nollywood trailer");
  const popularVideos = await getPopularVideos();

  return {
    props: { disneyVideos, tvShowsVideos, nollywoodVideos, popularVideos }
  }
}

export default function Home({ disneyVideos, tvShowsVideos, nollywoodVideos, popularVideos }) {


  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar username="ay.dev" />
        <Banner
          videoId="_cfOS75Rjms"
          title="Aja n le koko, part 2"
          subtitle="The dog is chasing the koko, will the dog catch the koko, find out now"
          imgUrl="https://images.unsplash.com/photo-1534361960057-19889db9621e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Nollywood" videos={nollywoodVideos} size="large" />
          <SectionCards title="TV shows" videos={tvShowsVideos} size="medium" />
          <SectionCards title="Disney" videos={disneyVideos} size="medium" />
          <SectionCards title="Continue Watching for Ay" videos={disneyVideos} size="small" />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </main>
    </>
  )
}
